global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # SNMP Exporter for MikroTik routers
  - job_name: 'snmp'
    scrape_interval: 15s
    scrape_timeout: 14s
    # Static target for VMware MikroTik CHR on VMnet8
    static_configs:
      - targets:
          - 192.168.247.2
        labels:
          hostname: VMware-Mikrotik-CHR
          device_id: '26'
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
